### ISSUE TITLE
Colour options

### ISSUE THREAD

**Issue by laianathestrange** [inimicus/CruxCounter#25]
**What do you want?** I want to be able to change the colour of the crux counter so it stands out more.

**Why do you want it?** Because it's hard for me to see it when I need it the most, e.g. when stacked up in trials where we're all arcs and all I can see is green XD

**Anything else?** That's all thanks, otherwise it's an epic add-on!

**Comment by inimicus** [comment]
That's a great idea, thank you!

In the meantime, all the colors are defined in `CruxCounter.xml`. Search for `color`, replace the hex values, reload UI, and huzzah.

I'm short on time, but hopefully will work this into an update soon.

Thanks again!
G
